github: ['ShenalSen']
patreon: # Add your Patreon username if applicable
open_collective: # Add your Open Collective username if applicable
ko_fi: # Add your Ko-fi username if applicable
tidelift: # Add your Tidelift package-name if applicable
community_bridge: # Add your Community Bridge project-name if applicable
liberapay: # Add your Liberapay username if applicable
issuehunt: # Add your IssueHunt username if applicable
lfx_crowdfunding: # Add your LFX Crowdfunding project-name if applicable
polar: # Add your Polar username if applicable
buy_me_a_coffee: # Add your Buy Me a Coffee username if applicable
thanks_dev: # Add your thanks.dev username if applicable
custom: ['https://github.com/sponsors/ShenalSen'] ['shenalsenarathne.me']

