# Generated by Django 5.1.4 on 2025-02-09 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('contact_number', models.CharField(max_length=15)),
                ('appointment_id', models.CharField(max_length=100)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
    ]
